# Generated by Django 6.0.3 on 2026-03-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_on_main',
            field=models.BooleanField(default=False),
        ),
    ]
